### ISSUE TITLE
[Suggestion] Additional permission for removing from list.

### ISSUE THREAD

**Issue by mrfloris** [pop4959/LWCTrust#1]
We might make this a perk for active regular players, and by default negate this for everybody. 

default group: 
negate

everybody higher than default group:
allow

However, it's possible that every once in a while there's someone who loses their privileges, like ex team member, or donator who charged back, etc.  They will then no longer be able to remove from the list. 

If I could add

default group:
negate main permission
but allow remove permission

and everybody higher than default group:
allow
allow to remove

Then this would solve that for us. 

I hereby kindly request an additional permission to allow groups specifically access to /trust remove <player> 
`lwctrust.trustremove`

**Comment by pop4959** [comment]
@mrfloris Sorry for taking so long, got busy and also got a new PC recently.

The primary permission node is still `lwctrust.trust` but it now includes sub nodes which can be individually toggled: `lwctrust.trust.add`, `lwctrust.trust.remove`, and `lwctrust.trust.list`.

In your case, all you should need to do is set `lwctrust.trust.remove: false` in your default group.
