### ISSUE TITLE
trust other command

### ISSUE THREAD

**Issue by seema84** [pop4959/LWCTrust#6]
Hey pop4959,

as already mentioned, a command for admins to perform trusts might be helpful.

example:

/trust [owner] [player]

maybe you find the idea also good and find sths time for it. thanks <3

**Comment by pop4959** [comment]
Sorry for the long delayed response. I have not looked at this for a while. I have thought about it, and I don't really think it makes sense for admins to add/remove trust from players. The whole point of trusting someone is giving access to all of a player's protections, which should be a player's choice. It's not at all similar in utility to forceowner in base LWC.

If you MUST do this, you should be able to edit the player's trust file easily (it's just regular json). I just don't think it makes sense to add a command for this unless there is a good reason why anyone would need this.
