### ISSUE TITLE
PlayerSetupGui for BlockOwner

### ISSUE THREAD

**Issue by ErythroCraft** [pop4959/LWCTrust#7]
Hi.

Is there a way to create an PlayerGui to enable users/players via sneak right-click to an PlayerSetupGui?

So, I want to create an PlayerSetupGui that should allow an owner of her/his blocks to open an
PlayerSetupGui by sneaking rightClickEvent. 

With this Gui she/he can setup members to allow open protected chests/blocks simplier.

Can you give an update?
Or, you have got an examle?

**Comment by pop4959** [comment]
I don't really plan on adding a GUI to this plugin, as LWC itself does not support any GUI features, sorry.
